### ISSUE TITLE
What a joke.

### ISSUE THREAD

**Issue by idgas01** [aligo/better-google#13]
The last time @aligo 's userscript broke, it took him five weeks to fix it.  This second time that it broke, it also took him another five weeks to fix it.  And then he didn't even fix it right!!!

This is  drwonky's userscript that he presented five weeks ago.  He basically just changed one element class name and that fixed aligo's userscript.:
![firefox_VLGvSUiUr3](https://user-images.githubusercontent.com/75463665/109165914-b947c480-7741-11eb-9542-71199f4e8d26.png)

This is @aligo 's updated userscript that he just published:
![firefox_PL2THor01w](https://user-images.githubusercontent.com/75463665/109165961-c6fd4a00-7741-11eb-9525-a3bb99af3b8b.png)

See the difference?  No?  Well then, something must be wrong with your eyes.

I think that the problem is @aligo half-arsed it and verified and approved the WRONG commit.  He was supposed to approve f866b71, and not 3b62234.
![firefox_hcwdUhhTzW](https://user-images.githubusercontent.com/75463665/109166358-3e32de00-7742-11eb-8492-ef39356201b3.png)

Way to go bro!  You finally logged in after five weeks and you couldn't even approve the right pull request.  Guess we have to wait another five weeks before you log in and approve the right one!

**Comment by aligo** [comment]
#12
