### ISSUE TITLE
Better Google is broken again

### ISSUE THREAD

**Issue by LogiFun** [aligo/better-google#14]
The formatting has been broken with this latest update... as the bits noted by the green arrows shouldn't be there:

![image](https://user-images.githubusercontent.com/79665711/109210636-b87b5680-7772-11eb-8316-114503d68341.png)

Anyone have any suggestions for a fix?

**Comment by aligo** [comment]
It seems that google is doing AB testing. My version don’t have these dots (-> #12 ?). Cloud you try the new script I just updated and tell me result, thanks.

**Comment by LogiFun** [comment]
Thanks for the response. And I just double-checked that I had version 0.1.16.3 and it is working as expected. Thank you.

Here is a screenshot....


![image](https://user-images.githubusercontent.com/79665711/109339625-82e77380-782d-11eb-97d9-32673a982a00.png)
