### ISSUE TITLE
Rendering/compatibility issue with uBlacklist Firefox addon

### ISSUE THREAD

**Issue by anonimuos** [aligo/better-google#9]
There is an addon for Chrome and Firefox called uBlacklist that lets you hide/blacklist sites from Google search results. I use it and your wonderful Better Google script with TamperMonkey in Google Chrome, other Chromium-based browsers and Mozilla Firefox.

No problems in Chrome.

But in Firefox, the text "Block this site" added by that addon, renders on the page like this after Better Google is installed: (Attached image):
![image](https://user-images.githubusercontent.com/46422834/104615721-8379df80-56af-11eb-8998-c6bd5686bec7.png)

Can you circumvent or fix it, please? :)

**Comment by toooonyy** [comment]
save here, my workaround now is to change 
`style.sheet.insertRule('.btrG { word-break: break-all; line-height: 18px; }');`
into
`style.sheet.insertRule('.btrG { word-break: normal; line-height: 18px; }');`

may have some side effects

**Comment by aligo** [comment]
12c18080ce9d386ec737bb9818ebf10cb8b8fa39
